services:
  postgres:
    image: postgres:16-alpine
    container_name: fastapi-postgres
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fastapi-network

  app:
    build: .
    container_name: fastapi-app
    environment:
      DB_URL: ${DB_URL}
      SECURITY_ALGORITHM: ${SECURITY_ALGORITHM}
      SECURITY_ACCESS_TOKEN_EXPIRE_MINUTES: ${SECURITY_ACCESS_TOKEN_EXPIRE_MINUTES}
      SWAGGER_DOCS_ROUTE: ${SWAGGER_DOCS_ROUTE}
      SWAGGER_REDOCS_ROUTE: ${SWAGGER_REDOCS_ROUTE}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fastapi-network
    volumes:
      - ./migrations:/app/migrations:ro
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fastapi-network:
    driver: bridge
